/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.IOFile;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MonHoc;
import model.QLDK;
import model.SinhVien;

/**
 *
 * @author Pham Thanh
 */
public class FormQLDK extends javax.swing.JPanel {

    /**
     * Creates new form FormQLDK
     */
    DefaultTableModel tm;
    private boolean t,s;
    private  String file;
    private List<QLDK> list;
    
    public FormQLDK() {
        initComponents();
        setSize(2000, 1000);
        String[] cols = {"Ma SV","Ten SV","Ma MH","Thoi gian"};
        tm = new DefaultTableModel(cols,0);
        jTable1.setModel(tm);
        file = "src/model/dk.dat";
        t = s = false;
        buttonTrue();
        List<SinhVien> lsv = IOFile.doc("src/model/sv.dat");
        List<MonHoc> lmh = IOFile.doc("src/model/mh.dat");
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        
        for(SinhVien i : lsv){
            jComboBox1.addItem(i.getMa()+ "");
        }
        for(MonHoc i : lmh){
            jComboBox2.addItem(i.getMa()+"");
        }
    }
    public void buttonTrue(){
        them.setEnabled(true);
        sua.setEnabled(true);
        capnhat.setEnabled(false);
        boqua.setEnabled(false);
    }
    public void buttonFalse(){
        them.setEnabled(false);
        sua.setEnabled(false);
        capnhat.setEnabled(true);
        boqua.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        luu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        hienthi = new javax.swing.JButton();
        them = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        sua = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        capnhat = new javax.swing.JButton();
        boqua = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        luu.setText("Luu file");
        luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuActionPerformed(evt);
            }
        });

        jLabel1.setText("Ma sv");

        hienthi.setText("Hien thi");
        hienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hienthiActionPerformed(evt);
            }
        });

        them.setText("Them");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        jLabel2.setText("Ma MH");

        sua.setText("Sua");
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });

        jButton3.setText("Xoa");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        capnhat.setText("Dang Ky");
        capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capnhatActionPerformed(evt);
            }
        });

        boqua.setText("Bo qua");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ten", "Thoi gian" }));

        jLabel3.setText("Sap xep theo");

        jButton1.setText("Sap xep");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, 109, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel4))
                .addGap(173, 173, 173))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(luu)
                    .addComponent(them))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sua)
                    .addComponent(hienthi))
                .addGap(38, 38, 38)
                .addComponent(capnhat)
                .addGap(55, 55, 55)
                .addComponent(boqua)
                .addGap(37, 37, 37)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(79, 79, 79)
                        .addComponent(jLabel4))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(them)
                    .addComponent(sua)
                    .addComponent(capnhat)
                    .addComponent(boqua)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luu)
                    .addComponent(hienthi)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public List<QLDK> getQLDK(){
        List<QLDK> list = new ArrayList<>();
        for (int i = 0; i < tm.getRowCount(); i++) {
          int masv = Integer.parseInt(tm.getValueAt(i, 0).toString());
          int mamh = Integer.parseInt(tm.getValueAt(i, 2).toString());
          SinhVien s = getSVbyMa(masv);
          MonHoc m = getMHbyMa(mamh);
          String time = tm.getValueAt(i, 2).toString();
          QLDK q = new QLDK(s, m, time);
          list.add(q);
//            list.add(new QLDK(ma,));
        }
        return list;
       
    }
    
    public boolean vipham(int masv, int mamh){
        int r = jTable1.getRowCount();
        for (int i = 0; i < r; i++) {
            if(Integer.parseInt(tm.getValueAt(i, 0).toString())==(masv) && Integer.parseInt(tm.getValueAt(i, 2).toString())==(mamh))
                return true;
        }
        
        return false;
    }
    
    private void luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuActionPerformed
        // TODO add your handling code here:
        List<QLDK> list = new ArrayList<>();
        list = getQLDK();
        //        System.out.println(l);
        IOFile.ghi(file,list);
    }//GEN-LAST:event_luuActionPerformed

    private void hienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hienthiActionPerformed
        // TODO add your handling code here:
        List<QLDK> list = IOFile.doc(file);
        tm.setRowCount(0);
        //        System.out.println(list);
        for(QLDK i : list){
            tm.addRow(i.toObject());
        }
    }//GEN-LAST:event_hienthiActionPerformed

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        // TODO add your handling code here:
        buttonFalse();
//        List<QLDK> l = getQLDK();
        t = true;
//        if(l.size()>0){}
//        QLDK.setSma(l.get(l.size()-1).getMa() + 1);

    }//GEN-LAST:event_themActionPerformed

    private void suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaActionPerformed
        // TODO add your handling code here:
        int r = jTable1.getSelectedRow();
        if(r<0 || r>=tm.getRowCount()){
            JOptionPane.showMessageDialog(this,"Chon dong can sua");
        }
        else {
//            jTextField2.requestFocus();
            s = true;
            buttonFalse();
        }
    }//GEN-LAST:event_suaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
//        jTextField1.setText(tm.getValueAt(i, 0).toString());
//        jTextField2.setText(tm.getValueAt(i, 1).toString());
//        jTextField3.setText(tm.getValueAt(i, 2).toString());
//        jTextField4.setText(tm.getValueAt(i, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked
    
    public SinhVien getSVbyMa(int masv){
        List<SinhVien> list = IOFile.doc("src/model/sv.dat");
        for(SinhVien i : list){
            if((i.getMa()==masv)) return i;
        }
        return null;
    }
    public MonHoc getMHbyMa(int masv){
        List<MonHoc> list = IOFile.doc("src/model/mh.dat");
        for(MonHoc i : list){
            if((i.getMa()==masv)) return i;
        }
        return null;
    }
    private void capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capnhatActionPerformed
        // TODO add your handling code here:
        if(t){
            t = false;
          int masv = Integer.parseInt(jComboBox1.getSelectedItem().toString());
          int mamh = Integer.parseInt(jComboBox2.getSelectedItem().toString());
          SinhVien s = getSVbyMa(masv);
          MonHoc m = getMHbyMa(mamh);
            SimpleDateFormat sf = new SimpleDateFormat("yyyy-mm-dd 'at' hh:mm:ss");
            Date date = new Date();
            String time = sf.format(date);
//            System.out.println(time + " ");
          QLDK q = new QLDK(s, m, time);
          if(vipham(masv, mamh)){
              JOptionPane.showMessageDialog(this, "Trung");
              
          }
          else tm.addRow(q.toObject());
        }
        if(s){
            s = false;
            int i = jTable1.getSelectedRow();
//            tm.setValueAt(jTextField1.getText(), i, 0);
//            tm.setValueAt(jTextField2.getText(), i, 1);
//            tm.setValueAt(jTextField3.getText(), i, 2);
//            tm.setValueAt(jTextField4.getText(), i, 3);

        }
        buttonTrue();
    }//GEN-LAST:event_capnhatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        List<QLDK> l = getQLDK();
        if(jComboBox3.getSelectedIndex()==1){
            l.sort(new Comparator<QLDK>() {
                @Override
                public int compare(QLDK o1, QLDK o2) {
                    String t1 = o1.getTg();
                    String t2 = o2.getTg();
                    return t1.compareToIgnoreCase(t2);
                }
            });
            
        }
        else {
            l.sort(new Comparator<QLDK>(){
                @Override
                public int compare(QLDK o1, QLDK o2) {
                    return o1.getSv().getTen().compareTo(o2.getSv().getTen());
                }
                
            });
        }
        tm.setRowCount(0);
        for(QLDK i : l) tm.addRow(i.toObject());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boqua;
    private javax.swing.JButton capnhat;
    private javax.swing.JButton hienthi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton luu;
    private javax.swing.JButton sua;
    private javax.swing.JButton them;
    // End of variables declaration//GEN-END:variables
}
