/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.IOFile;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MonHoc;

/**
 *
 * @author Pham Thanh
 */
public class FormMH extends javax.swing.JPanel {

    /**
     * Creates new form FormMH
     */
    DefaultTableModel tm;
    private boolean t,s;
    private  String file;
    private List<MonHoc> list;
    public FormMH() {
        initComponents();
        setSize(2000, 1000);
        String[] cols = {"Ma","Ten","So tiet","Loai"};
        tm = new DefaultTableModel(cols,0);
        jTable1.setModel(tm);
        file = "src/model/mh.dat";
        t = s = false;
        buttonTrue();
    }
    public void buttonTrue(){
        them.setEnabled(true);
        sua.setEnabled(true);
        capnhat.setEnabled(false);
        boqua.setEnabled(false);
    }
    public void buttonFalse(){
        them.setEnabled(false);
        sua.setEnabled(false);
        capnhat.setEnabled(true);
        boqua.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        them = new javax.swing.JButton();
        sua = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        capnhat = new javax.swing.JButton();
        luu = new javax.swing.JButton();
        hienthi = new javax.swing.JButton();
        boqua = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        them.setText("Them");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        sua.setText("Sua");
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });

        jButton3.setText("Xoa");

        capnhat.setText("Cap Nhat");
        capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capnhatActionPerformed(evt);
            }
        });

        luu.setText("Luu file");
        luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuActionPerformed(evt);
            }
        });

        hienthi.setText("Hien thi");
        hienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hienthiActionPerformed(evt);
            }
        });

        boqua.setText("Bo qua");

        jTextField1.setEditable(false);

        jLabel1.setText("Ma");

        jLabel2.setText("Ten Mon hoc");

        jLabel3.setText("So tiet");

        jLabel4.setText("Loai");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đại cương", "Cơ sở ngành", "Chuyên ngành bắt buộc", "Chuyên ngành tựchọn" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(30, 30, 30)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(65, 65, 65)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(luu)
                        .addGap(64, 64, 64)
                        .addComponent(hienthi))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(them)
                        .addGap(54, 54, 54)
                        .addComponent(sua)
                        .addGap(46, 46, 46)
                        .addComponent(capnhat)
                        .addGap(55, 55, 55)
                        .addComponent(boqua)
                        .addGap(37, 37, 37)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(them)
                    .addComponent(sua)
                    .addComponent(capnhat)
                    .addComponent(boqua)
                    .addComponent(jButton3))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luu)
                    .addComponent(hienthi))
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public List<MonHoc> getMH(){
        List<MonHoc> list = new ArrayList<>();
        for (int i = 0; i < tm.getRowCount(); i++) {
            int ma = Integer.parseInt(tm.getValueAt(i, 0).toString());
            String ten = tm.getValueAt(i, 1).toString();
            int sotiet = Integer.parseInt(tm.getValueAt(i, 2).toString());
            String loai = tm.getValueAt(i, 3).toString();
            list.add(new MonHoc(ma, ten, sotiet, loai));
        }
        return list;
       
    }
    
    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        // TODO add your handling code here:
        buttonFalse();
        List<MonHoc> l = getMH();
        t = true;
        if(l.size()>0)
            MonHoc.setSma(l.get(l.size()-1).getMa() + 1);
        
        jTextField1.setText(MonHoc.getSma() + "");
        jTextField2.requestFocus();
    }//GEN-LAST:event_themActionPerformed
    
    private void capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capnhatActionPerformed
        // TODO add your handling code here:
        if(t){
            t = false;
            int ma = Integer.parseInt(jTextField1.getText()); 
            String ten = jTextField2.getText();
            int sotiet = Integer.parseInt(jTextField3.getText());
            String loai = jComboBox1.getSelectedItem().toString();
            MonHoc m = new MonHoc(ma,ten,sotiet,loai);
            tm.addRow(m.toObject());
        }
        if(s){
            s = false;
            int i = jTable1.getSelectedRow();
            tm.setValueAt(jTextField1.getText(), i, 0);
            tm.setValueAt(jTextField2.getText(), i, 1);
            tm.setValueAt(jTextField3.getText(), i, 2);
            tm.setValueAt(jComboBox1.getSelectedItem(), i, 3);
           
        }
        buttonTrue();
    }//GEN-LAST:event_capnhatActionPerformed

    private void luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuActionPerformed
        // TODO add your handling code here:
        List<MonHoc> list = new ArrayList<>();
        list = getMH();
//        System.out.println(l);
        IOFile.ghi(file,list);
    }//GEN-LAST:event_luuActionPerformed

    private void hienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hienthiActionPerformed
        // TODO add your handling code here:
        List<MonHoc> list = IOFile.doc(file);
        tm.setRowCount(0);
//        System.out.println(list);
        for(MonHoc i : list){
            tm.addRow(i.toObject());
        }
    }//GEN-LAST:event_hienthiActionPerformed

    private void suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaActionPerformed
        // TODO add your handling code here:
        int r = jTable1.getSelectedRow();
        if(r<0 || r>=tm.getRowCount()){
            JOptionPane.showMessageDialog(this,"Chon dong can sua");
        }
        else {
            jTextField1.requestFocus();
            s = true;
            buttonFalse();
        }
    }//GEN-LAST:event_suaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        jTextField1.setText(tm.getValueAt(i, 0).toString());
        jTextField2.setText(tm.getValueAt(i, 1).toString());
        jTextField3.setText(tm.getValueAt(i, 2).toString());
        int indx = 0;
        for (int j = 0; j < jComboBox1.getComponentCount(); j++) {
            if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase(tm.getValueAt(i, 3).toString())){
                indx = j;
                break;
            }
            
        }
        jComboBox1.setSelectedItem(indx);
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boqua;
    private javax.swing.JButton capnhat;
    private javax.swing.JButton hienthi;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton luu;
    private javax.swing.JButton sua;
    private javax.swing.JButton them;
    // End of variables declaration//GEN-END:variables
}
