-- CREATE TABLE DVDuongBo(
-- 	MaDVDB VARCHAR(10) PRIMARY KEY,
--     SoBanh INT,
--     TrongTai INT,
--     FOREIGN KEY (MaDVDB) REFERENCES PhuongThuc(MaPT)
-- );
INSERT INTO DVDuongBo
VALUES ("DVDB1",4,300);
INSERT INTO DVDuongBo
VALUES ("DVDB2",8,1000);
INSERT INTO DVDuongBo
VALUES ("DVDB3",2,50);