-- CREATE TABLE NhanVienVC(
--     MaNVVC VARCHAR(10) PRIMARY KEY,
--     SoDonGiaoDich INT,
--     MucDanhGia INT,
--     FOREIGN KEY(MaNVVC) references NhanVien(MaNV)
-- );
INSERT INTO NhanVienVC
VALUES ("NV07",20,5);
INSERT INTO NhanVienVC
VALUES ("NV08",7,5);
INSERT INTO NhanVienVC
VALUES ("NV09",35,4);
INSERT INTO NhanVienVC
VALUES ("NV11",29,5);